
package InterfacesBingo;
import juegopackage.*;
/**
 *
 * @author daray
 */
public class juegoEnCursoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form juegoEnCursoInterfaz
     */
    public juegoEnCursoInterfaz() {
        initComponents();
        
        labelModoDeJuego.setText("Modo de Juego :"+ Bingo.getModoDeJuego());
        premioLabel.setText("Premio: " + Bingo.getPremio());
        totalDeCartonesLabel.setText("Total de cartones: " + Carton.getContador());
        totalDeJugadoresLabel.setText("Total de Jugadores: " + Jugador.getNumJugadores());
    }
    public void mostrarVentana(){
      this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModoDeJuego = new javax.swing.JLabel();
        premioLabel = new javax.swing.JLabel();
        cantarNumeroBoton = new javax.swing.JButton();
        numerosCantadosText = new javax.swing.JTextField();
        totalDeCartonesLabel = new javax.swing.JLabel();
        totalDeJugadoresLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelModoDeJuego.setText("mododejuego");

        premioLabel.setText("premio");

        cantarNumeroBoton.setBackground(new java.awt.Color(204, 204, 204));
        cantarNumeroBoton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cantarNumeroBoton.setText("Cantar número");
        cantarNumeroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantarNumeroBotonActionPerformed(evt);
            }
        });

        numerosCantadosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosCantadosTextActionPerformed(evt);
            }
        });

        totalDeCartonesLabel.setText("jLabel1");

        totalDeJugadoresLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(premioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalDeCartonesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalDeJugadoresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(numerosCantadosText, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(cantarNumeroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(premioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(labelModoDeJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(cantarNumeroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numerosCantadosText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDeJugadoresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDeCartonesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantarNumeroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantarNumeroBotonActionPerformed
        int numeroCantado = Bingo.cantarNumero();
        actualizarNumeros(numeroCantado);
    }//GEN-LAST:event_cantarNumeroBotonActionPerformed

    private void numerosCantadosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosCantadosTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosCantadosTextActionPerformed
    public void actualizarNumeros(int numero){
      String textoAnterior = numerosCantadosText.getText();
      String nuevoTexto = textoAnterior + ", " + numero;
      numerosCantadosText.setText(nuevoTexto);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juegoEnCursoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juegoEnCursoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juegoEnCursoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juegoEnCursoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juegoEnCursoInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cantarNumeroBoton;
    private javax.swing.JLabel labelModoDeJuego;
    private javax.swing.JTextField numerosCantadosText;
    private javax.swing.JLabel premioLabel;
    private javax.swing.JLabel totalDeCartonesLabel;
    private javax.swing.JLabel totalDeJugadoresLabel;
    // End of variables declaration//GEN-END:variables
}
